#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Blogger::Application.load_tasks


# desc
# task
# namespace
#

# rake noun:verb

namespace :tags do
  task :setup do
    puts "Loading this up for display reasons"
    # puts `ls -l`
  end

  desc "Clean up Ugly Tags"
  task :clean => [ :environment, :setup ] do
    
    Tag.all.each do |tag|
      # if the tag name contains an uppercase character then nuke it.
      if tag.name =~ /[A-Z]/
        puts "Destroying: #{tag.name}"
        tag.destroy
      end
    end
    
    puts "Cleaning Tags"
  end
  
  desc "List all tags"
  task :list => :environment do
    puts Tag.all.map {|tag| tag.name }.join(", ")
  end
end

